name: Deploy Ephemeral Environment

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

env:
  ENVIRONMENT_NAME: pr-${{ github.event.pull_request.number }}

jobs:
  policy-check:
    name: Policy Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.47.0/conftest_0.47.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.47.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Validate Kubernetes manifests
        run: |
          conftest test demo-app/kubernetes/*.yaml -p policies/

  deploy:
    name: Deploy Environment
    runs-on: ubuntu-latest
    needs: policy-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Deploy ephemeral environment
        run: |
          python cli/deploy.py deploy \
            --env-name ${{ env.ENVIRONMENT_NAME }} \
            --provider aws

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Environment deployed!\n\n Preview URL: https://${{ env.ENVIRONMENT_NAME }}.preview.example.com'
            })
